### ISSUE TITLE
Generation of environment.yml for mac

### ISSUE THREAD

**Issue by binho** [varungupta31/dashcam_anonymizer#2]
I'm trying the project on mac and I'm getting error:
```
(base) ➜  dashcam_anonymizer git:(master) ✗ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - x264=1!157.20191217
  - libvpx=1.7.0
  - libclang=10.0.1
  - libgfortran5=13.1.0
  - libstdcxx-ng=11.2.0
  - blas=1.1
  - ld_impl_linux-64=2.38
  - _libgcc_mutex=0.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libgfortran-ng=13.1.0
  - icu=58.2
  - _openmp_mutex=5.1
  - libxkbcommon=1.0.1
```

Is it possible to export a mac version with suggested command here?
https://stackoverflow.com/a/58160918

Thank you

**Comment by varungupta31** [comment]
@binho Hey, thanks for your interest in this project.
I see, I'm yet to find a concrete way to create completely reliable platform independent conda environment configs.

You may just `git pull` or `git clone` the repo again.

I have updated the repo now with a new Readme, and some other fixes, hope it solved the issue for you.
Just create from the new `.yaml` file,  and try again.

**Note**: Be careful processing long videos. In my M1, I got a segmentation fault parsing a 1500 frame video, so I guess a GPU would be required at a certain point, if not finding a way to optimise memory in the script.

If you still face issue in the environment (perhaps due to OS variations):
1. Create a conda environment with python.
2. pip install the opencv package [`pip install opencv-python==4.6.0.66` recommended]
4. Pip install `pybboxes` package.
5. Pip install the Ultralytics package [`pip install ultralytics`]
and you're all set!

Close the issue, if it works for you now.

**Comment by binho** [comment]
Thank you! Env file worked. I see the issue you mentioned regarding seg fault. I'll try to find something over here too 👍
