### ISSUE TITLE
How to process longer Video-Files ? 

### ISSUE THREAD

**Issue by graebec** [varungupta31/dashcam_anonymizer#3]
Hi there I just tested the tool, but it is not able to process bigger video files, because the option that is recommended "stream=true" isn't available. 

Any Idea ? 

Best regards

**Comment by varungupta31** [comment]
I processed 1 minute long videos @ 25 FPS fine.
I recently came across a much more effective video handler, [Decord](https://github.com/dmlc/decord). Which makes io more efficient. You could change the video reader using that, and see it it helps.

What exactly is the error when you say 'unable to process'?

If its system memory issues, i'm unaware how `cv2.VideoWriter` operates, but it may somewhere be accumulating things on the CPU memory. 

A fix would be to simply dump the blurred frames of a large video, and then create a video of it, rather than writing it with the writer which probably is accumulating stuff.
